common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from intelin.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('intelin/', include('intelin.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

intelin/urls.py
from django.urls import path
from .views import base_views, argument_views, refute_views

app_name = 'intelin'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:argument_id>/', base_views.detail, name='detail'),

    path('argument/create/', argument_views.argument_create, name='argument_create'),
    path('argument/modify/<int:argument_id>', argument_views.argument_modify, name='argument_modify'),
    path('argument/delete/<int:argument_id>', argument_views.argument_delete, name='argument_delete'),
    path('argument/vote/<int:argument_id>', argument_views.argument_vote, name='argument_vote'),

    path('refute/create/<int:argument_id>/', refute_views.refute_create, name='refute_create'),
    path('refute/modify/<int:refute_id>/', refute_views.refute_modify, name='refute_modify'),
    path('refute/delete/<int:refute_id>/', refute_views.refute_delete, name='refute_delete'),
    path('refute/vote/<int:refute_id>/', refute_views.refute_vote, name='refute_vote'),
]

intelin/models.py
from django.db import models
from django.contrib.auth.models import User


class Argument(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_argument')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가

    def __str__(self):
        return self.subject


class Refute(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_refute')
    argument = models.ForeignKey(Argument, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_refute')

intelin/forms.py
from django import forms
from intelin.models import Argument, Refute


class ArgumentForm(forms.ModelForm):
    class Meta:
        model = Argument
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '본론',
        }


class RefuteForm(forms.ModelForm):
    class Meta:
        model = Refute
        fields = ['content']
        labels = {
            'content': '본론',
        }

intelin/views/argument_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import ArgumentForm
from ..models import Argument


@login_required(login_url='common:login')
def argument_create(request):
    if request.method == "POST":
        form = ArgumentForm(request.POST)
        if form.is_valid():
            argument = form.save(commit=False)
            argument.author = request.user
            argument.create_date = timezone.now()
            argument.save()
            return redirect('intelin:index')
    else:
        form = ArgumentForm()
    context = {'form': form}
    return render(request, 'intelin/argument_form.html', context)

@login_required(login_url='common:login')
def argument_modify(request, argument_id):
    argument = get_object_or_404(Argument, pk=argument_id)
    if request.user != argument.author:
        messages.error(request, '아쎄이! 자네에겐 수정의 권한이 없다.') #Non-Field Error
        return redirect('intelin:detail', argument_id=argument.id)
    if request.method == 'POST':
        form = ArgumentForm(request.POST, instance=argument)
        if form.is_valid():
            argument = form.save(commit=False)
            argument.modify_date = timezone.now()
            argument.save()
            return redirect('intelin:detail', argument_id=argument.id)
    else:
        form = ArgumentForm(instance=argument)
    context = {'form': form}
    return render(request, 'intelin/argument_form.html', context)

@login_required(login_url='common:login')
def argument_delete(request, argument_id):
    argument = get_object_or_404(Argument, pk=argument_id)
    if request.user != argument.author:
        messages.error(request, '아쎄이! 자네에겐 기열시킬 권한이 없다')
        return redirect('intelin:detail', argument_id=argument.id)
    argument.delete()
    return redirect('intelin:index')

@login_required(login_url='common:login')
def argument_vote(request, argument_id):
    argument = get_object_or_404(Argument, pk= argument_id)
    if request.user == argument.author:
        messages.error(request, '기열!!! 스스로의 주장에 기합을 주려 하는가!')
    else:
        argument.voter.add(request.user)
    return redirect('intelin:detail', argument_id=argument.id)

intelin/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Argument


def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    argument_list = Argument.objects.order_by('-create_date')
    if kw:
        argument_list = argument_list.filter(
            Q(subject__icontains=kw)  |
            Q(content__icontains=kw)  |
            Q(refute__content__icontains=kw)  |
            Q(author__username__icontains=kw)  |
            Q(refute__author__username__icontains=kw)
        ).distinct()
    paginator = Paginator(argument_list, 10)
    page_obj = paginator.get_page(page)
    context = {'argument_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'intelin/argument_list.html', context)

def detail(request, argument_id):
    argument = get_object_or_404(Argument, pk=argument_id)
    context = {'argument': argument}
    return render(request, 'intelin/argument_detail.html', context)

intelin/views/refute_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import RefuteForm
from ..models import Argument, Refute

@login_required(login_url='common:login')
def refute_create(request, argument_id):
    argument = get_object_or_404(Argument, pk=argument_id)
    if request.method == "POST":
        form = RefuteForm(request.POST)
        if form.is_valid():
            refute = form.save(commit=False)
            refute.author = request.user
            refute.create_date = timezone.now()
            refute.argument = argument
            refute.save()
            return redirect('{}#refute_{}'.format(
                resolve_url('intelin:detail', argument_id=argument.id), refute.id))
    else:
        form = RefuteForm()
    context = {'argument': argument, 'form': form}
    return render(request, 'intelin/argument_detail.html', context)


@login_required(login_url='common:login')
def refute_modify(request, refute_id):
    refute = get_object_or_404(Refute, pk=refute_id)
    if request.user != refute.author:
        messages.error(request, '아쎄이! 자네에겐 수정의 권한이 없다.') #Non-Field Error
        return redirect('intelin:detail', argument_id=refute.argument.id)
    if request.method == 'POST':
        form = RefuteForm(request.POST, instance=refute)
        if form.is_valid():
            refute = form.save(commit=False)
            refute.modify_date = timezone.now()
            refute.save()
            return redirect('{}#refute_{}'.format(resolve_url('intelin:detail', argument_id=refute.argument.id), refute.id))
    else:
        form = RefuteForm(instance=refute)
    context = {'refute': refute, 'form': form}
    return render(request, 'intelin/refute_form.html', context)

@login_required(login_url='common:login')
def refute_delete(request, refute_id):
    refute = get_object_or_404(Refute, pk=refute_id)
    if request.user != refute.author:
        messages.error(request, '아쎄이! 자네에겐 기열의 권한이 없다')
    else:
        refute.delete()
    return redirect('intelin:detail', argument_id=refute.argument.id)

@login_required(login_url='common:login')
def refute_vote(request, refute_id):
    refute = get_object_or_404(Refute, pk=refute_id)
    if request.user == refute.author:
        messages.error(request, '기열!!! 스스로의 반박에 기합을 주려 하는가!')
    else:
        refute.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('intelin:detail', argument_id=refute.argument.id), refute.id))

templates/intelin/argument_detail.html
{% extends 'base.html' %}
{% load intelin_filter %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- What is role? What is tags?-->
    <!-- 주장 -->
    <h2 class="border-bottom py-2">{{ argument.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ argument.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if argument.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ argument.modify_date }}</div>
            </div>
            {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ argument.author.username }}</div>
                    <div>{{ argument.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            <a href="javascript:void(0)" data-uri="{% url 'intelin:argument_vote' argument.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 기합
                <span class="badge rounded-pill bg-success">{{argument.voter.count}}</span>
            </a>
            {% if request.user == argument.author %}
            <a href="{% url 'intelin:argument_modify' argument.id  %}"
               class="btn btn-sm btn-outline-secondary">찐빠</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'intelin:argument_delete' argument.id %}">기열</a>
            {% endif %}
            </div>
        </div>
    </div>
    <!-- 반박 -->
    <h5 class="border-bottom my-3 py-2">{{argument.refute_set.count}}개의 반박이 있습니다.</h5>
    {% for refute in argument.refute_set.all %}
        <a id="refute_{{ refute.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ refute.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ refute.author.username }}</div>
                    <div>{{ refute.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
            <a href="javascript:void(0)" data-uri="{% url 'intelin:refute_vote' refute.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 기합
                <span class="badge rounded-pill bg-success">{{refute.voter.count}}</span>
            </a>
            {% if request.user == refute.author %}
            <a href="{% url 'intelin:refute_modify' refute.id  %}"
               class="btn btn-sm btn-outline-secondary">번복</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'intelin:refute_delete' refute.id  %}">기열</a>
            {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 반박 등록 -->
    <form action="{% url 'intelin:refute_create' argument.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 기열하려던 것이 맞나?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 기합하려던 것이 맞나?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/intelin/argument_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">주장등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/intelin/argument_list.html
{% extends 'base.html' %}
{% load intelin_filter %}
{% block content %}
<img src="http://www.news-paper.co.kr/news/photo/202206/76955_50768_25.png" alt="표독한 얼굴 이미지" style="width: 300px">
<h3 class="border-bottom py-2">Intelin에 온 것을 환영합니다!</h3>
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'intelin:argument_create' %}" class="btn btn-primary">주장 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width: 50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if argument_list %}
        {% for argument in argument_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ argument_list.paginator.count|sub:argument_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'intelin:detail' argument.id %}">{{ argument.subject }}</a>
                {% if argument.refute_set.count %}
                <span class="text-danger small mx-2">{{ argument.refute_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ argument.author.username }}</td> <!-- 글쓴이 추가 -->
            <td>{{ argument.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">개소리가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 처음 페이지 -->
        {% if argument_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="1"
           href="javascript:void(0)"><</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><<</a>
        </li>
        {% endif %}
        <!-- 이전페이지 -->
        {% if argument_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ argument_list.previous_page_number }}"
           href="javascript:void(0)"><</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in argument_list.paginator.page_range %}
        {% if page_number >= argument_list.number|add:-5 and page_number <= argument_list.number|add:5 %}
        {% if page_number == argument_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if argument_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ argument_list.next_page_number }}"
               href="javascript:void(0)">></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">></a>
        </li>
        {% endif %}
        <!-- 마지막 페이지 -->
        {% if argument_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ argument_list.paginator.count|share:10|add:1 }}"
               href="javascript:void(0)">></a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#"></a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/intelin/refute_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}